project:
  type: website
  output-dir: _site
  render:
    - index.md
    - "*/lecture_*.md"
    - "!lectures_24/"
    - "!lectures_25/"
    - "!refs/"
    - "!scripts/"
    - "!overrides/"
    - "!.tmp/"
    - "!logs/"

website:
  title: "DataSci-223"
  site-url: https://christopherseaman.github.io/datasci_223
  repo-url: https://github.com/christopherseaman/datasci_223

format:
  html:
    theme: cyborg
    toc: true
    code-overflow: wrap

filters:
  - _filters/obsidian-callouts.lua
